import Foundation

enum L {
    static let strings: [String: (String, String)] = [
        "about": ("About Spice Client", "Spice Client について"), "quit": ("Quit Spice Client", "Spice Client を終了"),
        "menuFile": ("File", "ファイル"), "menuEdit": ("Edit", "編集"),
        "menuSession": ("Session", "セッション"), "menuWindow": ("Window", "ウィンドウ"),
        "minimize": ("Minimize", "しまう"), "Undo": ("Undo", "取り消す"), "Redo": ("Redo", "やり直す"),
        "Cut": ("Cut", "カット"), "Copy": ("Copy", "コピー"), "Paste": ("Paste", "ペースト"), "Select All": ("Select All", "すべてを選択"),
        "open": ("Open Connection File…", "接続ファイルを開く…"),
        "portal": ("Open Ravada Portal", "Ravada ポータルを開く"),
        "portalURL": ("HTTPS portal URL", "HTTPS ポータル URL"),
        "intro": ("Connect to a virtual machine with a .vv file or a Ravada portal.", ".vv ファイルまたは Ravada ポータルから仮想マシンに接続します。"),
        "confirm": ("Review Connection", "接続内容の確認"), "connect": ("Connect", "接続"),
        "cancel": ("Cancel", "キャンセル"), "close": ("Close", "閉じる"),
        "source": ("Source", "送信元"), "host": ("Host", "接続先"), "port": ("Port", "ポート"),
        "security": ("Connection protection", "通信の保護"),
        "plain": ("Unencrypted TCP — credentials and data can be observed on the network", "暗号化なしの TCP — ネットワーク上で認証情報やデータを読み取られる可能性があります"),
        "systemTLS": ("TLS · system certificate trust", "TLS · システムの証明書検証"),
        "customTLS": ("TLS · certificate authority from this file", "TLS · ファイルで指定された認証局"),
        "subjectTLS": ("TLS · file certificate authority and certificate subject", "TLS · ファイルの認証局と証明書サブジェクトを照合"),
        "clipboard": ("Share clipboard with this guest", "このゲストとクリップボードを共有"),
        "clipboardHelp": ("Sharing is off by default and only works while this session window has focus.", "共有は初期 OFF です。このセッションのウィンドウを操作している間だけ有効になります。"),
        "settings": ("Settings…", "設定…"), "trash": ("Move selected .vv files to Trash after a successful connection", "接続成功後、選択した .vv ファイルをゴミ箱に移動"),
        "clearLogin": ("Clear Portal Login Data", "ポータルのログイン情報を消去"),
        "cleared": ("Portal login data cleared.", "ポータルのログイン情報を消去しました。"),
        "disconnect": ("Disconnect", "切断"), "connecting": ("Connecting…", "接続中…"),
        "connected": ("Connected", "接続済み"), "stopping": ("Disconnecting…", "切断中…"),
        "closed": ("Disconnected", "切断済み"), "idle": ("Ready", "準備完了"),
        "diagnostics": ("Diagnostics", "診断情報"), "copy": ("Copy Summary", "集計をコピー"),
        "diagnosticsHelp": ("Aggregate counters only. Clipboard text, keys, credentials and screen contents are not recorded.", "集計値だけを記録します。クリップボードの内容、入力キー、認証情報、画面内容は記録しません。"),
        "cad": ("Send Ctrl-Alt-Delete", "Ctrl-Alt-Delete を送信"),
        "release": ("Release Input", "入力の捕捉を解除"), "fullscreen": ("Toggle Full Screen", "フルスクリーンを切り替え"),
        "portalRejected": ("The portal requested a connection file outside its allowed origin.", "許可された送信元以外から接続ファイルが要求されました。"),
        "downloadFailed": ("Could not retrieve a valid connection file. Check the portal login and try again.", "有効な接続ファイルを取得できませんでした。ポータルのログイン状態を確認して再試行してください。"),
        "unsupportedDownload": ("This download URL is unsupported. Save the .vv file and open it from the launcher.", "この形式のダウンロード URL は未対応です。.vv ファイルを保存し、ランチャーから開いてください。"),
        "portalFailed": ("The portal could not be loaded. Check its URL, network and certificate.", "ポータルを読み込めませんでした。URL、ネットワーク、証明書を確認してください。"),
        "certificatePrompt": ("Trust this portal certificate temporarily?", "このポータルの証明書を一時的に信頼しますか？"),
        "certificateTemporary": ("Verify this fingerprint with the administrator. Trust expires when this portal closes.", "管理者にこのフィンガープリントを確認してください。このポータルを閉じると承認は失効します。"),
        "trustOnce": ("Trust Until Portal Closes", "ポータルを閉じるまで信頼"),
        "busy": ("Review or cancel the current connection before opening another file.", "現在の接続候補を確認またはキャンセルしてから、次のファイルを開いてください。"),
        "invalidFile": ("The connection file is invalid or requests an unsupported option.", "接続ファイルが不正か、未対応の設定が指定されています。"),
        "invalidPort": ("A port is invalid. TLS settings will never fall back to an unencrypted connection.", "ポート指定が不正です。TLS 設定を暗号化なしの接続に切り替えることはありません。"),
        "tlsRequired": ("This file requires TLS but has no usable TLS endpoint.", "このファイルは TLS を要求していますが、有効な TLS 接続先がありません。"),
        "fileFailed": ("Could not read a regular .vv file (maximum 1 MiB).", "通常の .vv ファイルを読み込めませんでした（上限 1 MiB）。"),
        "trashFailed": ("Connected, but the original file was changed or could not be moved to Trash.", "接続しましたが、元ファイルが変更されたか、ゴミ箱へ移動できませんでした。"),
        "connection": ("Connection failed. Check the server, port, network and TLS certificate.", "接続に失敗しました。サーバー、ポート、ネットワーク、TLS 証明書を確認してください。"),
        "authentication": ("Authentication failed. Obtain a new connection file if its ticket has expired.", "認証に失敗しました。チケットの期限が切れた場合は接続ファイルを再取得してください。"),
        "protocolViolation": ("The server returned an unsupported or invalid SPICE message.", "サーバーから未対応または不正な SPICE メッセージを受信しました。"),
        "video": ("The required video codec is unavailable.", "必要な映像コーデックを利用できません。"),
        "input": ("Input transmission stalled or failed. The session has been stopped.", "入力の送信が停止または失敗したため、セッションを終了しました。"),
        "certificate": ("The connection file contains an invalid certificate.", "接続ファイルに不正な証明書が含まれています。"),
        "audioUnavailable": ("Audio playback is unavailable.", "音声再生を利用できません。"),
        "agentUnavailable": ("Guest integration is unavailable.", "ゲスト連携を利用できません。"),
        "noUpdates": ("Automatic updates are not included in this version.", "このバージョンには自動更新機能はありません。"),
    ]
    static func text(_ key: String, languages: [String] = Locale.preferredLanguages) -> String {
        guard let pair = strings[key] else { return key }
        return languages.first?.hasPrefix("ja") == true ? pair.1 : pair.0
    }
}
